Repository BHoM/MidasCivil_Toolkit, pull requests merged in 2020-05, with the labels that each got.

#209 Updated ReadMe file
  README.md
Labels: type:documentation

#216 Changing method from private to public
  MidasCivil_Adapter/CRUD/Read/Results/BarResults.cs
  MidasCivil_Adapter/CRUD/Read/Results/MeshResults.cs
Labels: severity:critical, size:S, type:bug

#218 Fixed incorrect reference for Azure Pipeline badge in ReadMe
  README.md
Labels: severity:low, size:XS, type:bug
