Repository BHoM/MidasCivil_Toolkit, pull requests merged in 2024-03, with the labels that each got.

#373 Fix a bug where REBAR-MATL-CODE creates an error when running mct file
  MidasCivil_Engine/Compute/CombineTextFiles.cs
Labels: size:S, type:bug

#376 Remove FixFix exception and remove bug for partial matches
  MidasCivil_Adapter/CRUD/Create/Elements/Element.cs
  MidasCivil_Adapter/CRUD/Create/Properties/BarReleases.cs
  MidasCivil_Adapter/PrivateHelpers/AssignBarRelease.cs
Labels: type:bug

#378 Fix beta-compliance-checks
  MidasCivil_Engine/Compute/CombineTextFiles.cs
  MidasCivil_Engine/Compute/FEMeshToPanel.cs
  MidasCivil_Engine/Create/Metadata.cs
Labels: type:compliance
